version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: auction-db
    environment:
      POSTGRES_DB: auctiondb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
