spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auctiondb
    username: admin
    password: admin
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
